/* 
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package TelstraTPN

type Flavor struct {

	// 
	Currency string `json:"currency,omitempty"`

	// 
	Description string `json:"description,omitempty"`

	// 
	Disk int32 `json:"disk,omitempty"`

	// 
	Ephemeral int32 `json:"ephemeral,omitempty"`

	// 
	Id int32 `json:"id,omitempty"`

	// 
	Name string `json:"name,omitempty"`

	// 
	Price float64 `json:"price,omitempty"`

	// 
	Ram int32 `json:"ram,omitempty"`

	// 
	SpecificCustomer string `json:"specific_customer,omitempty"`

	// 
	Swap int32 `json:"swap,omitempty"`

	// 
	Vcpus int32 `json:"vcpus,omitempty"`
}
