/*
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * API version: 2.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TelstraTPN

type InventoryLinkRequest struct {

	// 
	BillingId string `json:"billing-id,omitempty"`

	// 
	Description string `json:"description,omitempty"`

	// 
	Connections []string `json:"connections,omitempty"`

	// 
	Tag string `json:"tag,omitempty"`

	// Latency: 0=Low, 1=Standard, 2=Best Effort
	Latency int32 `json:"latency,omitempty"`

	// Duration of contract in minutes
	Duration int32 `json:"duration,omitempty"`

	// Bandwidth in kB/s
	Bandwidth int32 `json:"bandwidth,omitempty"`

	// Renewal Option: 0=Auto Disconnect, 1=Auto Renew, 2=Pay per hour
	RenewalOption int32 `json:"renewal-option,omitempty"`

	// 1=VLAN, 2=VNF
	LinkType int32 `json:"link-type,omitempty"`

	// 
	TopologyTagUuid string `json:"topology_tag_uuid,omitempty"`
}
