/* 
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package TelstraTPN

type Model100AccountResponse struct {

	// 
	Phone string `json:"phone,omitempty"`

	// 
	City string `json:"city,omitempty"`

	// 
	Fax string `json:"fax,omitempty"`

	// 
	Country string `json:"country,omitempty"`

	// 
	Address string `json:"address,omitempty"`

	// 
	State string `json:"state,omitempty"`

	// 
	Website string `json:"website,omitempty"`

	// 
	Companyuuid string `json:"companyuuid,omitempty"`

	// 
	Companyname string `json:"companyname,omitempty"`

	// 
	Postalcode string `json:"postalcode,omitempty"`

	// 
	Customertype string `json:"customertype,omitempty"`

	// 
	Status string `json:"status,omitempty"`

	// 
	Customeraccountid string `json:"customeraccountid,omitempty"`
}
